# Generated by Django 5.0.1 on 2024-07-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.CharField(max_length=6, verbose_name='Price')),
                ('image', models.ImageField(upload_to='store', verbose_name='Image')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Publish date')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-published'],
            },
        ),
    ]
