# Generated by Django 5.0.1 on 2024-07-25 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_seller_last_name_remove_seller_name_and_more'),
        ('store', '0002_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_seller', to='registration.seller', verbose_name='Seller'),
        ),
    ]
