# Generated by Django 5.0.1 on 2024-07-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Publish date'),
        ),
    ]
