# Generated by Django 5.0.1 on 2024-07-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='name',
        ),
        migrations.AddField(
            model_name='seller',
            name='direction',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Direction'),
        ),
    ]
