# Generated by Django 5.0.1 on 2024-07-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_seller_last_name_remove_seller_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['-user'], 'verbose_name': 'Seller', 'verbose_name_plural': 'Sellers'},
        ),
    ]
